### ISSUE TITLE
投稿

### ISSUE THREAD

**Issue by suiyun39** [HuaweiJoke/-Huawei-Joke#3]
某年年会

助理工程师, 普通工程师, 高工, 技术专家依次入场, 一个比一个技术精湛. 最后入场的是两个拿着U盘的人.

任我行很惊讶: 这两个人是谁? 竟然比我们的技术专家技术还高?

CTO看了一眼: 没见过

HRD看了一眼: 不是我们部门的

余大嘴说: 这两个是我们部门做胶片(PPT)的

**Comment by liuyounger** [comment]
这个没看懂

**Comment by HuaweiJoke** [comment]
已加
