### ISSUE TITLE
你真特么是个智障

### ISSUE THREAD

**Issue by beiliangshizi** [HuaweiJoke/-Huawei-Joke#5]

**Comment by beiliangshizi** [comment]
美帝企业工程师出事的时候没见你站出来，在这带节奏

**Comment by Frodez** [comment]
> 美帝企业工程师出事的时候没见你站出来，在这带节奏

这句话同样也可以用在你身上。你是谁啊，谁稀罕你谁天天盯着你站出来啊？

**Comment by guygubaby** [comment]
那没事了

**Comment by beiliangshizi** [comment]
> > 美帝企业工程师出事的时候没见你站出来，在这带节奏
> 
> 这句话同样也可以用在你身上。你是谁啊，谁稀罕你谁天天盯着你站出来啊？

世界上的不平事多了，没否认你抱不平，只是否认针对华为，就事论事。

**Comment by qeesung** [comment]
智障无疑

**Comment by alqscool** [comment]
确定是智障。。是不是那个智障李小儿

**Comment by alqscool** [comment]
大家一起投诉这卵玩意

**Comment by PPXComputer** [comment]
你对得起你的签名吗? 得之淡然，失之坦然，谦谦君子，温润如玉。 ????还搁炫呢?
